import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { TASTE_GRAVITY_EASTER_EGGS } from "../scripts/lib/observatory-snapshot.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (name) => fs.readFileSync(path.join(root, name), "utf8");

test("transparent planet icon is wired through Next metadata", () => {
  const icon = read("public/icon.svg");
  assert.match(icon, /🪐/u);
  assert.doesNotMatch(icon, /<rect\b/iu);
  assert.match(read("app/layout.tsx"), /\/icon\.svg/u);
  assert.equal(fs.existsSync(path.join(root, "app", "icon.svg")), false);
});

test("taste view exposes natural semantic poles and a selectable negative-infinity easter egg", () => {
  const taste = read("app/components/TasteMap.tsx");
  const css = read("app/globals.css");
  const cucumber = TASTE_GRAVITY_EASTER_EGGS.find((item) => item.restaurantLabel === "서브웨이" && item.menu === "오이샌드위치");
  assert.ok(cucumber && cucumber.score === 0 && cucumber.algorithmImpact === false);
  assert.match(taste, /← 비선호/u);
  assert.match(taste, /◇ 중립/u);
  assert.match(taste, /선호 →/u);
  assert.match(taste, /role="img"[\s\S]*선호도 축: 왼쪽 비선호 0퍼센트/u);
  assert.match(taste, /<small>0%<\/small>[\s\S]*<small>50%<\/small>[\s\S]*<small>100%<\/small>/u);
  assert.doesNotMatch(taste, /0% ·|50% ·|100% ·|좌우 위치|밝기 =|색 =/u);
  assert.match(taste, /taste-map__star taste-map__star--easter/u);
  assert.match(taste, />−∞<\/b>/u);
  assert.match(taste, /onSelectEasterEgg\(item\)/u);
  assert.match(taste, /TASTE_EASTER_EGG_LEFT = 11\.5/u);
  assert.doesNotMatch(taste, /DISPLAY ONLY|비선호 한계 밖|다시 피하고 싶음/u);
  assert.match(taste, /taste-map__list/u);
  assert.match(taste, /taste-map__list-item--easter/u);
  assert.match(taste, /sortMenusByTastePreference/u);
  assert.match(taste, /선호 순/u);
  assert.match(taste, /tastePercent\(menu\)/u);
  assert.match(taste, /aria-pressed/u);
  assert.match(taste, /TASTE_DOMAIN_START/u);
  assert.match(css, /\.taste-map__row\s*\{[^}]*left:\s*20%/su);
  assert.match(css, /\.taste-map__star--easter/u);
  assert.doesNotMatch(css, /taste-map__star--forbidden/u);
  const observatory = read("app/components/Observatory.tsx");
  assert.match(observatory, /selectedEasterEgg[\s\S]*연구실 공식 금지 메뉴입니다\.[\s\S]*detail-infinity[\s\S]*−∞/u);
  assert.doesNotMatch(observatory, /취향 지도 한쪽에 숨어 있는 이스터에그입니다/u);
});

test("cosmos is layered, motion-aware, lightweight, and disposes every custom GPU resource", () => {
  const observatory = read("app/components/Observatory.tsx");
  const cosmos = read("app/components/MenuCosmos.tsx");
  const css = read("app/globals.css");
  assert.match(observatory, /const visibleTaxonomy = useMemo/u);
  assert.match(observatory, /taxonomy=\{visibleTaxonomy\}/u);
  assert.match(observatory, /easterEggs=\{visibleTasteEasterEggs\}/u);
  assert.doesNotMatch(observatory, /requestFullscreen|전체 화면/u);
  assert.match(cosmos, /createCollisionForce/u);
  assert.match(cosmos, /kind:\s*"anomaly"/u);
  assert.match(cosmos, /취향 −∞/u);
  const spiralCount = Number(cosmos.match(/const spiralCount = (\d+)/u)?.[1]);
  assert.ok(spiralCount >= 420 && spiralCount <= 1200, "cosmic detail stays within its particle budget");
  assert.match(cosmos, /const flareCount = 96/u);
  assert.match(cosmos, /nebula-arcs/u);
  assert.match(cosmos, /category-hub/u);
  assert.match(cosmos, /IcosahedronGeometry/u);
  assert.match(cosmos, /visibleLabelPositions/u);
  assert.match(cosmos, /gargantua-facing/u);
  assert.match(cosmos, /buildLensedArc/u);
  assert.match(cosmos, /ShaderPass/u);
  assert.match(cosmos, /uniform float lensRadius/u);
  assert.match(cosmos, /photonRing/u);
  assert.match(cosmos, /eventHorizonMask/u);
  assert.match(cosmos, /float lensMask = step/u);
  assert.doesNotMatch(cosmos, /float active\s*=/u);
  assert.match(cosmos, /onSelectEasterEggRef\.current/u);
  assert.match(cosmos, /requestAnimationFrame\(updateLensing\)/u);
  assert.match(cosmos, /cancelAnimationFrame\(lensingAnimationFrame\)/u);
  assert.doesNotMatch(cosmos, /onRenderFramePre/u);
  assert.match(cosmos, /const stars = 1080/u);
  assert.match(cosmos, /const dustCount = 260/u);
  assert.match(cosmos, /RingGeometry\(185, 535, 96\)/u);
  assert.match(cosmos, /AdditiveBlending/u);
  assert.match(cosmos, /FogExp2/u);
  assert.match(cosmos, /prefers-reduced-motion: reduce/u);
  assert.match(cosmos, /media\.addEventListener\("change"[\s\S]*media\.removeEventListener/u);
  assert.match(cosmos, /linkVisibility\(\(\) => false\)/u);
  assert.match(cosmos, /linkDirectionalParticles\(0\)/u);
  assert.doesNotMatch(cosmos, /haloColor|taste\?\.bias/u);
  assert.match(cosmos, /cosmos-accessibility-note/u);
  assert.match(cosmos, /disposeObject\(starField\)/u);
  assert.match(cosmos, /for \(const decoration of cosmicDecorations\)[\s\S]*disposeObject\(decoration\)/u);
  assert.match(cosmos, /scene\(\)\.fog = null/u);
  assert.match(cosmos, /bloomPass\?\.dispose/u);
  assert.match(cosmos, /webglcontextlost/u);
  assert.match(css, /\.menu-cosmos__atmosphere/u);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)/u);
  assert.doesNotMatch(cosmos, /menus\.filter\(\(item\) => item\.category === menu\.category\)/u);
});

test("responsive UI keeps labels legible and reroll cards concise on narrow screens", () => {
  const reroll = read("app/components/RerollShop.tsx");
  const observatory = read("app/components/Observatory.tsx");
  const css = read("app/globals.css");
  assert.match(reroll, /rollingTimerRef[\s\S]*clearTimeout/u);
  assert.match(reroll, /aria-live="polite"/u);
  assert.doesNotMatch(observatory, /viewport-footer/u);
  assert.match(reroll, /reroll-card__price/u);
  assert.doesNotMatch(reroll, /회 등장|추천 이력 없음/u);
  assert.match(css, /\.reroll-card__price\s*\{[^}]*text-overflow:\s*ellipsis/su);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.reroll-card\s*\{[^}]*flex:\s*0 0 166px/su);
  assert.match(css, /\.taste-map__semantic-pole b\s*\{[^}]*font-size:\s*16px/su);
  assert.match(css, /\.taste-map__row span\s*\{[^}]*font:[^;}]*14px/su);
  assert.match(css, /\.search-field input\s*\{[^}]*height:\s*100%/su,
    "the input itself must fill its 40-42px visible target, not only its wrapper");
  assert.match(css, /\.reroll-card__category\s*\{[^}]*font-size:\s*12px/su);
  assert.match(css, /\.taste-rail__pole\s*\{[^}]*width:\s*12px[^}]*height:\s*12px/su);
  assert.doesNotMatch(read("app/layout.tsx"), /next\/font|Noto_Sans_KR/u);
  assert.match(css, /--font-sans:\s*"Pretendard Variable"[^;]*"Noto Sans KR"[^;]*system-ui/u);
  assert.match(read("scripts/build-sites.mjs"), /absolute local build path/u);
  assert.doesNotMatch(observatory, /READ ONLY|SELECTED OBJECT|OBJECTS|CLUSTER/u);
});

test("snapshot loads once, keeps a last-known-good fallback, and excludes internal metadata", () => {
  const observatory = read("app/components/Observatory.tsx");
  const taste = read("app/components/TasteRail.tsx");
  const css = read("app/globals.css");
  assert.doesNotMatch(observatory, /setInterval|visibilitychange|SNAPSHOT_REVALIDATE/u);
  assert.match(observatory, /15_000/u);
  assert.match(observatory, /\["\/api\/snapshot\/current", "\/data\/snapshot\.json"\]/u);
  assert.match(observatory, /validateSnapshot\(JSON\.parse\(snapshotText\)\)/u);
  assert.match(observatory, /이 브라우저에 저장된 메뉴를 표시합니다/u);
  assert.match(observatory, /nextCategorySelection\(selectedCategories, category, categoryIds\)/u);
  assert.doesNotMatch(observatory, /최초 추천일 필터|현재 근거|추천 묶음|선호 점수|선호 반영 방식|데이터 최신/u);
  assert.doesNotMatch(observatory, />갱신 | · 확인 /u);
  assert.match(observatory, /aria-label=\{paused \? "자동 회전 켜기" : "자동 회전 끄기"\}/u);
  assert.doesNotMatch(read("app/components/MenuCosmos.tsx").split("pausedRef.current = paused;").at(-1), /pauseAnimation|resumeAnimation/u);
  assert.doesNotMatch(css, /\.pause-button\s*\{[^}]*font-size:\s*0/gu);
  assert.match(observatory, /<dt>가격<\/dt>/u);
  assert.match(observatory, /<dt>배달<\/dt>/u);
  assert.match(observatory, /최근 배달 가능 확인/u);
  assert.match(observatory, /최근 배달 운영 확인/u);
  assert.match(observatory, /배달 정보 없음/u);
  assert.match(taste, /선호도 \$\{percentage\}/u);
  assert.doesNotMatch(taste, /반영 강도|근거 충분|정보 부족|실제 식사 반영|선호 응답 반영/u);
});
